-- Límites operativos por nivel de debida diligencia.
-- GENERADO desde seeders/minimos/03-limites-operativos.json — no editar a mano.

INSERT INTO limite_operativo_billetera (concepto, nivel_debida_diligencia, ventana, monto_maximo, cantidad_maxima, moneda, base_normativa, vigente_desde, activo) VALUES
  ('SALDO_MAXIMO', 'SIMPLIFICADA', 'OPERACION', 2000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('SALDO_MAXIMO', 'ESTANDAR', 'OPERACION', 5000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('SALDO_MAXIMO', 'AMPLIADA', 'OPERACION', 20000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('SALDO_MAXIMO', 'REFORZADA', 'OPERACION', 50000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'SIMPLIFICADA', 'OPERACION', 1000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'SIMPLIFICADA', 'MES', 6000, 20, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'SIMPLIFICADA', 'OPERACION', 1000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'SIMPLIFICADA', 'DIA', 2000, 3, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'SIMPLIFICADA', 'MES', 6000, 20, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'SIMPLIFICADA', 'OPERACION', 1000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'SIMPLIFICADA', 'MES', 6000, 30, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'SIMPLIFICADA', 'OPERACION', 1000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'SIMPLIFICADA', 'MES', 6000, 30, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'ESTANDAR', 'OPERACION', 2500, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'ESTANDAR', 'MES', 25000, 60, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'ESTANDAR', 'OPERACION', 2500, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'ESTANDAR', 'DIA', 7000, 5, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'ESTANDAR', 'MES', 25000, 60, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'ESTANDAR', 'OPERACION', 2500, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'ESTANDAR', 'MES', 25000, 90, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'ESTANDAR', 'OPERACION', 2500, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'ESTANDAR', 'MES', 25000, 90, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'AMPLIADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'AMPLIADA', 'MES', 80000, 200, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'AMPLIADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'AMPLIADA', 'DIA', 20000, 10, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'AMPLIADA', 'MES', 80000, 200, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'AMPLIADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'AMPLIADA', 'MES', 80000, 300, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'AMPLIADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'AMPLIADA', 'MES', 80000, 300, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'REFORZADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RECARGA', 'REFORZADA', 'MES', 150000, 300, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'REFORZADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'REFORZADA', 'DIA', 35000, 10, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('RETIRO', 'REFORZADA', 'MES', 150000, 300, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'REFORZADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('TRANSFERENCIA', 'REFORZADA', 'MES', 150000, 500, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'REFORZADA', 'OPERACION', 7000, NULL, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE),
  ('APORTE', 'REFORZADA', 'MES', 150000, 500, 'BOB', 'PROVISIONAL — confirmar con legal contra el reglamento vigente del BCB y la RNSF', current_date, TRUE)
ON CONFLICT DO NOTHING;
